type OptionalString = optional<union<string, null, undefined>>

type ScriptPropertiesOption1 = arguments<string, OptionalString, OptionalString, OptionalString>

object ScriptPropertiesOption2 {
    name: string
    description: OptionalString
    author: OptionalString
    version: OptionalString
}

type ScriptProperties = union<ScriptPropertiesOption1, arguments<ScriptPropertiesOption2>>


-- c++ exported module
module aegisub {
    version: string
    set_script_properties: function<ScriptProperties, void>
}
