name: Flatpak build

on:
    release:
        types: [published]
    push:
        branches: ["master"]
    pull_request:
    workflow_dispatch:

jobs:
    flatpak:
        name: "Flatpak build"
        runs-on: ubuntu-22.04
        container:
            image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
            options: --privileged
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6.1
              with:
                  bundle: aegisub.flatpak
                  manifest-path: org.aegisub.Aegisub.yml
                  run-tests: false
