name: Flatpak build

on:
  release:
    types: [published]
  push:
    branches: [flatpak]
  workflow_dispatch:
env:
  CC: gcc-11
  CXX: g++-11

jobs:
  flatpak:
    name: "Flatpak build org.aegisub.Aegisub"
    runs-on: ubuntu-22.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3
        with:
          repository: tinywrkb/flathub
          ref: org.freedesktop.Sdk.Extension.wxwidgets
      - name: Build wxWidgest Extension
        run: flatpak-builder  wx-build/ org.freedesktop.Sdk.Extension.wxwidgets.yaml
      - name: Install built Flatpak Extension
        run: flatpak-builder --user --install  --force-clean  wx-build/ org.freedesktop.Sdk.Extension.wxwidgets.yaml
      - name: Go back to root
        run: cd ..
      - uses: actions/checkout@v3
        with:
          ref: flatpak
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: aegisub.flatpak
          manifest-path: org.aegisub.Aegisub.yml
          run-tests: true
